### DISCUSSION TITLE
Ideation for Milestone 4 (0.2.0)

### DISCUSSION THREAD

**Discussion by joelanford** [operator-framework/operator-controller#184] [Release Planning] [answered]
Hi! Now that we've made lots of progress on Milestone 3's major pushes (`.spec.version`, `.spec.channel`, and catalogd integration), it is time again that we begin establishing our next milestone.

# Progress Recap

To begin with, let's recap the progress we've made thus far. As of Milestone 3, we will have:
1. Added the `spec.version` field in the Operator API, which enables cluster admins to optionally contrain resolution by pinning the operator to a specific version.
2. Added the `spec.channel` field in the Operator API, which enables cluster admins to optionally constrain resolution to select versions in a specific channel.
3. Added an integration with `catalogd`, which is planned as OLMv1's new project for making FBC catalogs available on a cluster.
4. As part of (3), revert our temporary support for (and also dependency on) OLMv0 and it's `CatalogSource` API.

Thus, we have the stage set for operator-controller 0.2.0 (Milestone 4).

# Milestone 4 Ideas

This list is _much_ too large to include everything. But I think the following ideas are somewhat unblocked and ready to be worked on, so its worth discussing which of these things we think would be most impactful in three key areas:
1. What will make people interested in trying out OLMv1 and giving us feedback?
2. What will help us test a hypothesis to give us information about a future milestone?
3. What will improve upon the foundation we have and make future milestones easier to implement and maintain?

## Operator Controller
- Improve the contents of the `Operator` status struct. Possibilities include:
  - Adding `status.installedVersion` and `status.resolvedVersion`.
  - Changing our condition types to include `Installed` and `Resolved`.
  - Removing or re-defining the meaning of the existing `Ready` condition.
- Trigger re-reconciliation of all `Operator` objects when any of the available catalogs' data has changed.
- Add support for a catalog source label selector in the Operator API. If not specified, the bundle resolved for this operator can come from any catalog. If it is specified, the bundle resolved for this operator must come from one of the matching Catalog objects.
- Add support for honoring upgrade edges defined in the catalog.
- Think about ways to define upgrade policy. Today the implicit policy is "as soon as possible" and "automatically".

## Catalogd
- Add a Rukpak-like `spec.source` union type to the `Catalog` API, which would allow catalog filesystems to be sourced in a variety of ways. It would also give catalogd developers an extensible API surface to add new source mechanisms in the future.
- Continue iterating on the catalogd API surface, For example: remove the `Package` and `BundleMetadata` CRDs and replace with an aggregated-apiserver that serves a more generic `CatalogMetadata` API.
- Iterate on the `Catalog` status, and make it minimally usable for clients to understand the current state of the catalog. Examples include:
   - Were there issues unpacking or parsing the catalog content defined in the `spec`?
   - What is the hash of the catalog content currently being served?
   - Is the currently served catalog metadata representative of the current `Catalog` spec (or is it stale/out-of-date?).
       - This could happen if we successfully unpacked and started serving at time 0, and then the spec changed and we fail to unpack/parse the new catalog data. Do we keep serving the old data? Or do we serve nothing?

## Rukpak
- Add a kustomize provisioner and/or improve the helm provisioner. These two types may be the sweet spot because they give flexibility to both cluster admins and operator authors (plain manifest bundles and registry+v1 bundles are not very flexible).
- Implement a new bundle source for pulling and unpacking images in-process, as a sibling to the CRI-based `image` source Rukpak currently supports. This source would be necessary to consume potential OLM OCI bundles and Helm OCI bundles.
- Investigate ideas related to introspecting bundle health and upgrade readiness. This will eventually be necessary information as input into the operator-controller resolver so that it can understand which operators can be upgraded.

## Tenancy
- Begin brainstorming various possibilities and tradeoffs tenancy features and approaches for OLMv1 operators, which are installed no more than once per cluster.

# Potential demo scripts and coast-to-coast story arcs

## Detecting catalog changes and re-reconciling Operator objects
1. Create a `Catalog` object referencing `quay.io/joelanford/example-operator-index:0.1.0`
2. Show that the catalog status reflects that it was successfully unpacked.
3. Show that the catalogd metadata api reports objects for all packages, channels, and bundles in the catalog.
4. Create an `Operator` object referencing package `example-operator`
5. Show that a `BundleDeployment` gets created and references the bundle image `quay.io/joelanford/example-operator-bundle:0.1.0`
6. Update the `Catalog` object to reference a new image: `quay.io/joelanford/example-operator-index:0.2.0`
7. Show that the existing `BundleDeployment` is updated to reflect a new bundle image reference with `quay.io/joelanford/example-operator-bundle:0.2.0`
8. Delete the `Operator` and `Catalog` objects.
9. Show that no catalog metadata or bundle deployment objects remain.

## Sourcing catalog content from a ConfigMap
1. Create this `ConfigMap`:
    ```yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: example-operator-index
      namespace: catalogd-system
    data:
      catalog.json: |
        {"defaultChannel":"stable","name":"example-operator","schema":"olm.package"}
        {"entries":[{"name":"example-operator.v0.1.0"}],"name":"stable","package":"example-operator","schema":"olm.channel"}
        {"image":"quay.io/joelanford/example-operator-bundle:0.1.0","name":"example-operator.v0.1.0","package":"example-operator","properties":[{"type":"olm.gvk","value":{"group":"example.com","kind":"App","version":"v1"}},{"type":"olm.package","value":{"packageName":"example-operator","version":"0.1.0"}}],"relatedImages":[{"image":"quay.io/joelanford/example-operator-bundle:0.1.0","name":""},{"image":"quay.io/joelanford/example-operator@sha256:a5f8fce740945fcdabf7f8ac6fcd6f0f95b3a828fbf17e43de251de9d5544118","name":""}],"schema":"olm.bundle"}
    ```
2. Create this `Catalog`:
    ```yaml
    ---
    apiVersion: operatorframework.io/v1alpha1
    kind: Catalog
    metadata:
      name: example-operator-index
    spec:
      source:
        type: configMaps
        configMaps:
        - configMap:
            name: example-operator-index
          path: configs
    ```
3. Show that the catalog status reflects that it was successfully unpacked.
4. Show that the catalogd metadata api reports objects for all packages, channels, and bundles in the catalog.
5. Create an `Operator` object referencing package `example-operator`
6. Show that a `BundleDeployment` gets created and references the bundle image `quay.io/joelanford/example-operator-bundle:0.1.0`
7. Delete the `Operator` and `Catalog` objects.
8. Show that no catalog metadata or bundle deployment objects remain.

## Reporting failures in the `Catalog` object.
1. Create a `Catalog` object referencing image `quay.io/foobar/foobar:latest`
2. Show that the catalog object's status reports a failure sourcing the catalog content.

## Reporting the hash of the `Catalog` content in the catalog's status
1. Create a `Catalog` object referencing `quay.io/joelanford/example-operator-index:0.1.0`
2. Show that the catalog status contains a hash that represents contents of the catalog.
3. Update the catalog object to reference `quay.io/joelanford/example-operator-index:0.2.0`
4. Show that the catalog status contains a different hash for the new contents of the catalog.
5. Update the catalog object to reference `quay.io/joelanford/example-operator-index:0.1.0`
6. Show that the catalog status contains the same hash that was seen in step 2.
