### ISSUE TITLE
ClusterExtension - tls: failed to verify certificate

### ISSUE THREAD

**Issue by psimms-cs** [operator-framework/operator-controller#1162]
I am trying to setup quay-operator on my k8 cluster

I have setup the below
- operator-controller - v0.13.0 - Using install.sh
- catalogd - v0.20.0 - Using install.sh
- operatorhubio clusterCatalog setup with insecureSkipTLSVerify set to true 
- quay-operator clusterExtension

But I am getting a tls verify error for the clusterExtenstion
```
      message: >-
        error fetching image descriptor: Get "https://quay.io/v2/": tls: failed
        to verify certificate: x509: certificate signed by unknown authority
```

Can I skip this like for clusterCatalog?

clusterCatalog
```
apiVersion: catalogd.operatorframework.io/v1alpha1
kind: ClusterCatalog
metadata:
  name: operatorhubio
spec:
  source:
    type: image
    image:
      ref: quay.io/operatorhubio/catalog:latest
      insecureSkipTLSVerify: true
      pollInterval: 10m
```

clusterExtenstion
```
apiVersion: olm.operatorframework.io/v1alpha1
kind: ClusterExtension
metadata:
  name: project-quay-cluster-extension
spec:
  installNamespace: quay-enterprise
  serviceAccount:
    name: default
  packageName: project-quay
  channel: stable-3.12
  version: 3.12.0
```
