### ISSUE TITLE
Combine catalogd and operator-controller goreleaser configurations

### ISSUE THREAD

**Issue by OchiengEd** [operator-framework/operator-controller#1342]
Combine goreleaser files from the catalogd and operator-controller files.

**Comment by jsm84** [comment]
Linked to internal Jira issue EET-4420.

**Comment by LalatenduMohanty** [comment]
We can use GoReleaser within a monorepo and use tag prefixes to mark "which tags belong to which sub project" [1] 

[1] https://goreleaser.com/customization/monorepo/

**Comment by LalatenduMohanty** [comment]
We can create a .goreleaser.yaml for each subproject 
```
# subroj1/.goreleaser.yaml
project_name: subproj1

monorepo:
  tag_prefix: subproject1/
  dir: subproj1

```

Then, you can release with (from the project's root directory):
```
goreleaser release --clean -f ./subproj1/.goreleaser.yaml
```
