### ISSUE TITLE
[bug/ux] don't know what catalog image tag I  was using before

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/operator-controller#1360]
Say we create a ClusterCatalog pointing to `my-catalog:1` and it succeeds, we then go and point to my-catalog:2, which maybe doesn't exist. If you inspect the conditions you can see:
 - the error (@ generation _n_)
 - that it's available (@ generation _n_ - 1)
 - the image reference my-catalog@sha256... 

The issue is that it's not trivial to recover the original image (i.e. my-catalog:1), since we resolve to the sha'ed image reference.

Maybe we should either:
a) include the original input in the resolved source stanza to look something like:

```yaml
resolvedSource:
image:
  lastSuccessfulPollAttempt: "2024-10-10T07:12:43Z"
  image: my-catalog:1
  ref: my-catalog@sha256:2f6ba3fc28b4ef4b99027855681be8b8fe0962d931afc1ca5120f626f7416486
type: Image
```

b) make `.spec.source` immutable once set
