### ISSUE TITLE
[bug/ux] unreachable bundle error message

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/operator-controller#1361]
If I have a package with channel:

```yaml
entries:
- name: my-package.v1.0.0
- name: my-package.v1.0.1
  replaces: my-package.v1.0.0
- name: my-package.v1.0.2
  replaces: my-package.v1.0.1
name: stable
package: my-package
schema: olm.channel
```

If I install v1.0.0, then try to go to v1.0.2 I'd see the following condition:

```
    Last Transition Time:  2024-10-10T06:49:34Z
    Message:               error upgrading from currently installed version "1.0.0": no bundles found for package "my-package" matching version "1.0.2"
    Observed Generation:   2
    Reason:                Retrying
    Status:                True
    Type:                  Progressing
```

The message suggests that there is no bundle v1.0.2, which isn't strictly true. The problem is that the upgrade graph doesn't let me go to it.
