### ISSUE TITLE
Add status.installedBundleSource

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-controller#199]
Introduce the status.installedBundleSource which should reflect the bundle image sha/git commit which can be derived from [this structure](https://github.com/operator-framework/rukpak/blob/0876db6a30de0aaa6ce5651e2e24f5f6d5766e22/api/v1alpha1/bundle_types.go#L61-L78) in the RukPak bundle status.

A corresponding condition should exist which represents whether or not the operator is installed:
```
 Status:
  conditions:
    - type: "Installed"
       status: "False"
       reason: "PrettyBigBad"
       message: "The package does not exist"
       observedGeneration: 2
```
