### ISSUE TITLE
Add status.resolvedBundleSource

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-controller#202]
Once the operator-controller has used the deppy library to solve the solution, it should know "what it's going to install next" for a given operator CR. We can showcase this information in the status in a new resolvedBundleSource field.

A corresponding condition should exist which represents whether or not the operator was resolved:
```
 Status:
  conditions:
    - type: "Resolved"
       status: "False"
       reason: "BigBad"
       message: "The package does not exist"
       observedGeneration: 2
```
