### ISSUE TITLE
webhookDefinitions are not supported registry+v1=> plain+v0

### ISSUE THREAD

**Issue by DrummyFloyd** [operator-framework/operator-controller#749]
Hi, OLM team!

# OLM
`version: 0.9.0`

## others components
```
catalogd_version=v0.12.0
cert_mgr_version=v1.9.0
rukpak_version=v0.19.0
```
# behaviour

atm, this is not possible to use the latest operators from https://operatorhub.io/
when i try  latest's one, i have this error

`Message: convert registry+v1 bundle to plain+v0 bundle: webhookDefinitions are not supported`

tested upon the following manifests.

```yaml
---
apiVersion: catalogd.operatorframework.io/v1alpha1
kind: Catalog
metadata:
  name: operatorhubio
spec:
  source:
    type: image
    image:
      ref: quay.io/operatorhubio/catalog:latest
      pollInterval: 24h
---
apiVersion: olm.operatorframework.io/v1alpha1
kind: ClusterExtension
metadata:
  name: operatorhubio-argocd-operator
spec:
  packageName: argocd-operator
  version: 0.8.0
---
apiVersion: olm.operatorframework.io/v1alpha1
kind: ClusterExtension
metadata:
  name: operatorhubio-loki-operator
spec:
  packageName: loki-operator
  version: 0.6.0
---
apiVersion: olm.operatorframework.io/v1alpha1
kind: ClusterExtension
metadata:
  name: operatorhubio-gitlab-runner
spec:
  packageName: gitlab-runner-operator
  version: 1.15.1
```
