### ISSUE TITLE
Add new required field to ClusterExtension spec for users to reference a ServiceAccount

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-controller#971]
In order to begin using a `ServiceAccount` to install and manage content, a user needs to be able to specify a `ServiceAccount` for operator-controller to use when creating a `ClusterExtension`. Since OLMv1 will not have any permissions for installing and managing permissions by default this will need to be a required, immutable field.

An example of what a `ClusterExtension` resource could look like with this additional field:
```yaml
apiVersion: olm.operatorframework.io/v1alpha1
kind: ClusterExtension
metadata:
  name: clusterextension-sample
spec:
  installNamespace: default
  packageName: argocd-operator
  version: 0.6.0
  serviceAccount:
    name: argocd-installer
```

**Acceptance Criteria**:
- A new required, immutable field in the `ClusterExtension` spec for specifying a `ServiceAccount` that should be used to install and manage content
- Updates to unit and e2e tests as necessary
